//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilerSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarSet()
        {
            this.SpareSet = new HashSet<SpareSet>();
        }
    
        public int Id { get; set; }
        public int IdClient { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Color { get; set; }
        public string GosNumber { get; set; }
        public string Engine { get; set; }
        public string VinNumber { get; set; }
    
        public virtual ClientSet ClientSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpareSet> SpareSet { get; set; }
    }
}
