//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilerSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpareSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpareSet()
        {
            this.OrderSpareSet = new HashSet<OrderSpareSet>();
            this.Services = new HashSet<Services>();
        }
    
        public int Id { get; set; }
        public int IdCar { get; set; }
        public string Name { get; set; }
        public string Maker { get; set; }
        public int Count { get; set; }
        public double Price { get; set; }
    
        public virtual CarSet CarSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSpareSet> OrderSpareSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}
